controller_list:
  - name: fake_r_leg_controller
    joints:
      - r_hip_yaw_joint
      - r_hip_roll_joint
      - r_hip_pitch_joint
      - r_knee_pitch_joint
      - r_ankle_pitch_joint
      - r_ankle_roll_joint
  - name: fake_l_leg_controller
    joints:
      - l_hip_yaw_joint
      - l_hip_roll_joint
      - l_hip_pitch_joint
      - l_knee_pitch_joint
      - l_ankle_pitch_joint
      - l_ankle_roll_joint